package siif.v.demo;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import siif.v.cronometro.CronometroFuncionando;


public class telaPrincipal extends javax.swing.JFrame {
    private final String arqBandeiras = "bandeiras.siif";
    
    private CronometroFuncionando cron;

    /**
     * Creates new form NovoJFrameImagem
     */
    public telaPrincipal() {
        
        
        initComponents();
        ajustarBotoes(false);
        
        ajustarBandeiras();
        setLocationRelativeTo(null);
    }
    
    public void ajustarBandeiras(){
        FileReader arquivo;
        try {
         arquivo = new FileReader(arqBandeiras);             
         BufferedReader Ler = new BufferedReader(arquivo);
         String linha = Ler.readLine();
                  
         b01.setEnabled(converte(linha)); linha = Ler.readLine();
         b02.setEnabled(converte(linha)); linha = Ler.readLine();
         b03.setEnabled(converte(linha)); linha = Ler.readLine();
         b04.setEnabled(converte(linha)); linha = Ler.readLine();
         b05.setEnabled(converte(linha)); linha = Ler.readLine();
         b06.setEnabled(converte(linha)); linha = Ler.readLine();
         b07.setEnabled(converte(linha)); linha = Ler.readLine();
         b08.setEnabled(converte(linha)); linha = Ler.readLine();
         b09.setEnabled(converte(linha)); linha = Ler.readLine();
         b10.setEnabled(converte(linha)); linha = Ler.readLine();
         b11.setEnabled(converte(linha)); linha = Ler.readLine();
         b12.setEnabled(converte(linha)); linha = Ler.readLine();
         b13.setEnabled(converte(linha)); linha = Ler.readLine();
         b14.setEnabled(converte(linha)); linha = Ler.readLine();
         b15.setEnabled(converte(linha)); linha = Ler.readLine();
         b16.setEnabled(converte(linha)); linha = Ler.readLine();
         b17.setEnabled(converte(linha)); linha = Ler.readLine();
         b18.setEnabled(converte(linha)); linha = Ler.readLine();
         b19.setEnabled(converte(linha)); linha = Ler.readLine();
         b20.setEnabled(converte(linha)); linha = Ler.readLine();
         b21.setEnabled(converte(linha)); linha = Ler.readLine();
         b22.setEnabled(converte(linha)); linha = Ler.readLine();
         b23.setEnabled(converte(linha)); linha = Ler.readLine();
         b24.setEnabled(converte(linha)); linha = Ler.readLine();
         b25.setEnabled(converte(linha)); linha = Ler.readLine();
         b26.setEnabled(converte(linha)); linha = Ler.readLine();
         b27.setEnabled(converte(linha)); linha = Ler.readLine();
         b28.setEnabled(converte(linha)); linha = Ler.readLine();
         b29.setEnabled(converte(linha)); linha = Ler.readLine();
         b30.setEnabled(converte(linha)); linha = Ler.readLine();
         b31.setEnabled(converte(linha)); linha = Ler.readLine();
         b32.setEnabled(converte(linha)); linha = Ler.readLine();
         b33.setEnabled(converte(linha)); linha = Ler.readLine();
         b34.setEnabled(converte(linha)); linha = Ler.readLine();
         b35.setEnabled(converte(linha)); linha = Ler.readLine();
         b36.setEnabled(converte(linha));
         
         Ler.close();
         arquivo.close();
         
        } catch (FileNotFoundException ex) {
            Logger.getLogger(telaConfig.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(telaConfig.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private boolean converte(String valor){
     return valor.equals("true");
    }

    public void mostraBandeira(String bandeira) {
        String caminho;
        caminho = "/imagem/b"+bandeira+".png";
        ImageIcon grafico = new ImageIcon(getClass().getResource(caminho));
        logo.setIcon(grafico);
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        b01 = new javax.swing.JButton();
        b02 = new javax.swing.JButton();
        b03 = new javax.swing.JButton();
        b04 = new javax.swing.JButton();
        b07 = new javax.swing.JButton();
        b08 = new javax.swing.JButton();
        b09 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        b13 = new javax.swing.JButton();
        b14 = new javax.swing.JButton();
        b15 = new javax.swing.JButton();
        b25 = new javax.swing.JButton();
        b20 = new javax.swing.JButton();
        b21 = new javax.swing.JButton();
        b16 = new javax.swing.JButton();
        b31 = new javax.swing.JButton();
        b19 = new javax.swing.JButton();
        b22 = new javax.swing.JButton();
        b33 = new javax.swing.JButton();
        b32 = new javax.swing.JButton();
        b28 = new javax.swing.JButton();
        b27 = new javax.swing.JButton();
        b34 = new javax.swing.JButton();
        b26 = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        resultado = new javax.swing.JLabel();
        btnParar = new javax.swing.JButton();
        txtSegundos = new javax.swing.JTextField();
        txtMinutos = new javax.swing.JTextField();
        bandGrande = new javax.swing.JLabel();
        bandGrande2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        b05 = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        b06 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        b18 = new javax.swing.JButton();
        b17 = new javax.swing.JButton();
        b23 = new javax.swing.JButton();
        b24 = new javax.swing.JButton();
        b30 = new javax.swing.JButton();
        b29 = new javax.swing.JButton();
        b35 = new javax.swing.JButton();
        b36 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 700));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/b05.png"))); // NOI18N

        b01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/b01_.png"))); // NOI18N
        b01.setBorder(null);
        b01.setBorderPainted(false);
        b01.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b01ActionPerformed(evt);
            }
        });

        b02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/b02_.png"))); // NOI18N
        b02.setBorder(null);
        b02.setBorderPainted(false);
        b02.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b02ActionPerformed(evt);
            }
        });

        b03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/b03_.png"))); // NOI18N
        b03.setBorder(null);
        b03.setBorderPainted(false);
        b03.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b03ActionPerformed(evt);
            }
        });

        b04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/b04_.png"))); // NOI18N
        b04.setBorder(null);
        b04.setBorderPainted(false);
        b04.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b04ActionPerformed(evt);
            }
        });

        b07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/b05_.png"))); // NOI18N
        b07.setBorder(null);
        b07.setBorderPainted(false);
        b07.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b07ActionPerformed(evt);
            }
        });

        b08.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/b06_.png"))); // NOI18N
        b08.setBorder(null);
        b08.setBorderPainted(false);
        b08.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b08ActionPerformed(evt);
            }
        });

        b09.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/b07_.png"))); // NOI18N
        b09.setBorder(null);
        b09.setBorderPainted(false);
        b09.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b09ActionPerformed(evt);
            }
        });

        b10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/b08_.png"))); // NOI18N
        b10.setBorder(null);
        b10.setBorderPainted(false);
        b10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });

        b13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/b09_.png"))); // NOI18N
        b13.setBorder(null);
        b13.setBorderPainted(false);
        b13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b13ActionPerformed(evt);
            }
        });

        b14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/b10_.png"))); // NOI18N
        b14.setBorder(null);
        b14.setBorderPainted(false);
        b14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b14ActionPerformed(evt);
            }
        });

        b15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/b11_.png"))); // NOI18N
        b15.setBorder(null);
        b15.setBorderPainted(false);
        b15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b15ActionPerformed(evt);
            }
        });

        b25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/b17_.png"))); // NOI18N
        b25.setBorder(null);
        b25.setBorderPainted(false);
        b25.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b25ActionPerformed(evt);
            }
        });

        b20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/b14_.png"))); // NOI18N
        b20.setBorder(null);
        b20.setBorderPainted(false);
        b20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b20ActionPerformed(evt);
            }
        });

        b21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/b15_.png"))); // NOI18N
        b21.setBorder(null);
        b21.setBorderPainted(false);
        b21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b21ActionPerformed(evt);
            }
        });

        b16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/b12_.png"))); // NOI18N
        b16.setBorder(null);
        b16.setBorderPainted(false);
        b16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b16ActionPerformed(evt);
            }
        });

        b31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/b21_.png"))); // NOI18N
        b31.setBorder(null);
        b31.setBorderPainted(false);
        b31.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b31ActionPerformed(evt);
            }
        });

        b19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/b13_.png"))); // NOI18N
        b19.setBorder(null);
        b19.setBorderPainted(false);
        b19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b19ActionPerformed(evt);
            }
        });

        b22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/b16_.png"))); // NOI18N
        b22.setBorder(null);
        b22.setBorderPainted(false);
        b22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b22ActionPerformed(evt);
            }
        });

        b33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/b23_.png"))); // NOI18N
        b33.setBorder(null);
        b33.setBorderPainted(false);
        b33.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b33ActionPerformed(evt);
            }
        });

        b32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/b22_.png"))); // NOI18N
        b32.setBorder(null);
        b32.setBorderPainted(false);
        b32.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b32ActionPerformed(evt);
            }
        });

        b28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/b20_.png"))); // NOI18N
        b28.setBorder(null);
        b28.setBorderPainted(false);
        b28.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b28ActionPerformed(evt);
            }
        });

        b27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/b19_.png"))); // NOI18N
        b27.setBorder(null);
        b27.setBorderPainted(false);
        b27.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b27ActionPerformed(evt);
            }
        });

        b34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/b24_.png"))); // NOI18N
        b34.setBorder(null);
        b34.setBorderPainted(false);
        b34.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b34ActionPerformed(evt);
            }
        });

        b26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/b18_.png"))); // NOI18N
        b26.setBorder(null);
        b26.setBorderPainted(false);
        b26.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b26ActionPerformed(evt);
            }
        });

        btnIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/siif/v/demo/iniciar.png"))); // NOI18N
        btnIniciar.setBorder(null);
        btnIniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        resultado.setBackground(new java.awt.Color(255, 255, 255));
        resultado.setFont(new java.awt.Font("Agency FB", 1, 170)); // NOI18N
        resultado.setForeground(new java.awt.Color(51, 51, 51));
        resultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultado.setText("00:00");

        btnParar.setBackground(new java.awt.Color(51, 51, 51));
        btnParar.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnParar.setForeground(new java.awt.Color(51, 51, 51));
        btnParar.setText("Parar");
        btnParar.setBorder(null);
        btnParar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPararActionPerformed(evt);
            }
        });

        txtSegundos.setBackground(new java.awt.Color(51, 51, 51));
        txtSegundos.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        txtSegundos.setForeground(new java.awt.Color(255, 255, 255));
        txtSegundos.setText("0");

        txtMinutos.setBackground(new java.awt.Color(51, 51, 51));
        txtMinutos.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        txtMinutos.setForeground(new java.awt.Color(255, 255, 255));
        txtMinutos.setText("3");
        txtMinutos.setToolTipText("");

        bandGrande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/siif/v/demo/ONU.png"))); // NOI18N

        bandGrande2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/siif/v/demo/SIIF.png"))); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/config.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        b05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/b25_.png"))); // NOI18N
        b05.setBorder(null);
        b05.setBorderPainted(false);
        b05.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b05ActionPerformed(evt);
            }
        });

        b11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/b26_.png"))); // NOI18N
        b11.setBorder(null);
        b11.setBorderPainted(false);
        b11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });

        b06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/b31_.png"))); // NOI18N
        b06.setBorder(null);
        b06.setBorderPainted(false);
        b06.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b06ActionPerformed(evt);
            }
        });

        b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/b32_.png"))); // NOI18N
        b12.setBorder(null);
        b12.setBorderPainted(false);
        b12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12ActionPerformed(evt);
            }
        });

        b18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/b33_.png"))); // NOI18N
        b18.setBorder(null);
        b18.setBorderPainted(false);
        b18.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b18ActionPerformed(evt);
            }
        });

        b17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/b27_.png"))); // NOI18N
        b17.setBorder(null);
        b17.setBorderPainted(false);
        b17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b17ActionPerformed(evt);
            }
        });

        b23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/b28_.png"))); // NOI18N
        b23.setBorder(null);
        b23.setBorderPainted(false);
        b23.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b23ActionPerformed(evt);
            }
        });

        b24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/b37_.png"))); // NOI18N
        b24.setBorder(null);
        b24.setBorderPainted(false);
        b24.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b24ActionPerformed(evt);
            }
        });

        b30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/b35_.png"))); // NOI18N
        b30.setBorder(null);
        b30.setBorderPainted(false);
        b30.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b30ActionPerformed(evt);
            }
        });

        b29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/b29_.png"))); // NOI18N
        b29.setBorder(null);
        b29.setBorderPainted(false);
        b29.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b29ActionPerformed(evt);
            }
        });

        b35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/b30_.png"))); // NOI18N
        b35.setBorder(null);
        b35.setBorderPainted(false);
        b35.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b35ActionPerformed(evt);
            }
        });

        b36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/b36_.png"))); // NOI18N
        b36.setBorder(null);
        b36.setBorderPainted(false);
        b36.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        b36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b36ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logo)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bandGrande2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(397, 397, 397)
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bandGrande))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(137, 137, 137)
                                        .addComponent(txtMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtSegundos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnParar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnIniciar))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b05)
                        .addGap(9, 9, 9)
                        .addComponent(b11)
                        .addGap(9, 9, 9)
                        .addComponent(b17)
                        .addGap(9, 9, 9)
                        .addComponent(b23)
                        .addGap(9, 9, 9)
                        .addComponent(b29)
                        .addGap(9, 9, 9)
                        .addComponent(b35))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b06)
                        .addGap(9, 9, 9)
                        .addComponent(b12)
                        .addGap(9, 9, 9)
                        .addComponent(b18)
                        .addGap(9, 9, 9)
                        .addComponent(b24)
                        .addGap(9, 9, 9)
                        .addComponent(b30)
                        .addGap(9, 9, 9)
                        .addComponent(b36))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b03)
                        .addGap(9, 9, 9)
                        .addComponent(b09)
                        .addGap(9, 9, 9)
                        .addComponent(b15)
                        .addGap(9, 9, 9)
                        .addComponent(b21)
                        .addGap(9, 9, 9)
                        .addComponent(b27)
                        .addGap(9, 9, 9)
                        .addComponent(b33))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b04)
                        .addGap(9, 9, 9)
                        .addComponent(b10)
                        .addGap(9, 9, 9)
                        .addComponent(b16)
                        .addGap(9, 9, 9)
                        .addComponent(b22)
                        .addGap(9, 9, 9)
                        .addComponent(b28)
                        .addGap(9, 9, 9)
                        .addComponent(b34))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b01)
                                .addGap(9, 9, 9)
                                .addComponent(b07)
                                .addGap(9, 9, 9)
                                .addComponent(b13)
                                .addGap(9, 9, 9)
                                .addComponent(b19))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b02, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(b08)
                                .addGap(9, 9, 9)
                                .addComponent(b14)
                                .addGap(9, 9, 9)
                                .addComponent(b20)))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b26)
                                .addGap(9, 9, 9)
                                .addComponent(b32))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b25)
                                .addGap(9, 9, 9)
                                .addComponent(b31)))))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bandGrande)
                            .addComponent(bandGrande2)
                            .addComponent(jButton1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSegundos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnParar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnIniciar)))
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b01)
                    .addComponent(b07)
                    .addComponent(b13)
                    .addComponent(b19)
                    .addComponent(b25)
                    .addComponent(b31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b02)
                    .addComponent(b08)
                    .addComponent(b14)
                    .addComponent(b20)
                    .addComponent(b26)
                    .addComponent(b32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b03)
                    .addComponent(b09)
                    .addComponent(b15)
                    .addComponent(b21)
                    .addComponent(b27)
                    .addComponent(b33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b04)
                    .addComponent(b10)
                    .addComponent(b16)
                    .addComponent(b22)
                    .addComponent(b28)
                    .addComponent(b34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b05)
                    .addComponent(b11)
                    .addComponent(b17)
                    .addComponent(b23)
                    .addComponent(b29)
                    .addComponent(b35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b06)
                    .addComponent(b12)
                    .addComponent(b18)
                    .addComponent(b24)
                    .addComponent(b30)
                    .addComponent(b36))
                .addGap(82, 82, 82))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // semelhante ao onClick
    
    private void b01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b01ActionPerformed
        mostraBandeira("01");//África
    }//GEN-LAST:event_b01ActionPerformed

    private void b02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b02ActionPerformed
        mostraBandeira("02");//Alemanha
    }//GEN-LAST:event_b02ActionPerformed

    private void b03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b03ActionPerformed
        mostraBandeira("03");//Argentina
    }//GEN-LAST:event_b03ActionPerformed

    private void b04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b04ActionPerformed
         mostraBandeira("04");//Austrália
    }//GEN-LAST:event_b04ActionPerformed

    private void b07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b07ActionPerformed
         mostraBandeira("05");//Brasil
    }//GEN-LAST:event_b07ActionPerformed

    private void b08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b08ActionPerformed
         mostraBandeira("06");//Canadá
    }//GEN-LAST:event_b08ActionPerformed

    private void b09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b09ActionPerformed
         mostraBandeira("07");//China
    }//GEN-LAST:event_b09ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
         mostraBandeira("08");//Coreia do Norte
    }//GEN-LAST:event_b10ActionPerformed

    private void b13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b13ActionPerformed
         mostraBandeira("09");//Coréia do Sul
    }//GEN-LAST:event_b13ActionPerformed

    private void b14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b14ActionPerformed
         mostraBandeira("10");//Cuba
    }//GEN-LAST:event_b14ActionPerformed

    private void b15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b15ActionPerformed
         mostraBandeira("11");//EUA
    }//GEN-LAST:event_b15ActionPerformed

    private void b25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b25ActionPerformed
        mostraBandeira("17");//França
    }//GEN-LAST:event_b25ActionPerformed

    private void b20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b20ActionPerformed
         mostraBandeira("14");//Paraguai
    }//GEN-LAST:event_b20ActionPerformed

    private void b21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b21ActionPerformed
         mostraBandeira("15");//Irã
    }//GEN-LAST:event_b21ActionPerformed

    private void b16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b16ActionPerformed
         mostraBandeira("12");//Iraque
    }//GEN-LAST:event_b16ActionPerformed

    private void b31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b31ActionPerformed
        mostraBandeira("21");//Israel
    }//GEN-LAST:event_b31ActionPerformed

    private void b19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b19ActionPerformed
         mostraBandeira("13");//Itália
    }//GEN-LAST:event_b19ActionPerformed

    private void b22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b22ActionPerformed
         mostraBandeira("16");//Japão
    }//GEN-LAST:event_b22ActionPerformed

    private void b33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b33ActionPerformed
        mostraBandeira("23");//Panamá
    }//GEN-LAST:event_b33ActionPerformed

    private void b32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b32ActionPerformed
        mostraBandeira("22");//Índia
    }//GEN-LAST:event_b32ActionPerformed

    private void b28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b28ActionPerformed
        mostraBandeira("20");//Rússia
    }//GEN-LAST:event_b28ActionPerformed

    private void b27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b27ActionPerformed
        mostraBandeira("19");//Turquia
    }//GEN-LAST:event_b27ActionPerformed

    private void b34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b34ActionPerformed
        mostraBandeira("24");//Venezuela
    }//GEN-LAST:event_b34ActionPerformed
            
    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        if (txtMinutos.getText().equals("") || txtSegundos.getText().equals("")) {
            System.out.println("Informe o tempo!");
            return;
        }
        cron = new CronometroFuncionando(this,
                Integer.parseInt(txtMinutos.getText()),
                Integer.parseInt(txtSegundos.getText()));
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void b26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b26ActionPerformed
        mostraBandeira("18");//Reino Unido
    }//GEN-LAST:event_b26ActionPerformed

    private void btnPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPararActionPerformed
        if (cron != null) {
            if (cron.theadPrograma.isAlive()) {
                cron.theadPrograma.interrupt();
                resultado.setText("00:00");
                ajustarBotoes(false);
            }
        }
    }//GEN-LAST:event_btnPararActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        telaConfig tela = new telaConfig(this);       
        tela.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void b05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b05ActionPerformed
        mostraBandeira("25");//
    }//GEN-LAST:event_b05ActionPerformed

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
        mostraBandeira("26");//
    }//GEN-LAST:event_b11ActionPerformed

    private void b06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b06ActionPerformed
        mostraBandeira("31");//
    }//GEN-LAST:event_b06ActionPerformed

    private void b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12ActionPerformed
        mostraBandeira("32");//
    }//GEN-LAST:event_b12ActionPerformed

    private void b18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b18ActionPerformed
        mostraBandeira("33");//
    }//GEN-LAST:event_b18ActionPerformed

    private void b17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b17ActionPerformed
        mostraBandeira("27");//
    }//GEN-LAST:event_b17ActionPerformed

    private void b23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b23ActionPerformed
        mostraBandeira("28");//
    }//GEN-LAST:event_b23ActionPerformed

    private void b24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b24ActionPerformed
        mostraBandeira("37");//
    }//GEN-LAST:event_b24ActionPerformed

    private void b30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b30ActionPerformed
        mostraBandeira("35");//
    }//GEN-LAST:event_b30ActionPerformed

    private void b29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b29ActionPerformed
        mostraBandeira("29");//
    }//GEN-LAST:event_b29ActionPerformed

    private void b35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b35ActionPerformed
        mostraBandeira("30");//
    }//GEN-LAST:event_b35ActionPerformed

    private void b36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b36ActionPerformed
        mostraBandeira("36");//
    }//GEN-LAST:event_b36ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPrincipal().setVisible(true);
            }
        });
    }

    public void ajustarBotoes(boolean iniciou) {
        getBtnIniciar().setEnabled(!iniciou);
        getBtnParar().setEnabled(iniciou);
    }

    public JButton getBtnIniciar() {
        return btnIniciar;
    }

    public JButton getBtnParar() {
        return btnParar;
    }

    public JLabel getResultado() {
        return resultado;
    }

    public JTextField getTxtMinutos() {
        return txtMinutos;
    }

    public JTextField getTxtSegundos() {
        return txtSegundos;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b01;
    private javax.swing.JButton b02;
    private javax.swing.JButton b03;
    private javax.swing.JButton b04;
    private javax.swing.JButton b05;
    private javax.swing.JButton b06;
    private javax.swing.JButton b07;
    private javax.swing.JButton b08;
    private javax.swing.JButton b09;
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b13;
    private javax.swing.JButton b14;
    private javax.swing.JButton b15;
    private javax.swing.JButton b16;
    private javax.swing.JButton b17;
    private javax.swing.JButton b18;
    private javax.swing.JButton b19;
    private javax.swing.JButton b20;
    private javax.swing.JButton b21;
    private javax.swing.JButton b22;
    private javax.swing.JButton b23;
    private javax.swing.JButton b24;
    private javax.swing.JButton b25;
    private javax.swing.JButton b26;
    private javax.swing.JButton b27;
    private javax.swing.JButton b28;
    private javax.swing.JButton b29;
    private javax.swing.JButton b30;
    private javax.swing.JButton b31;
    private javax.swing.JButton b32;
    private javax.swing.JButton b33;
    private javax.swing.JButton b34;
    private javax.swing.JButton b35;
    private javax.swing.JButton b36;
    private javax.swing.JLabel bandGrande;
    private javax.swing.JLabel bandGrande2;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnParar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel resultado;
    private javax.swing.JTextField txtMinutos;
    private javax.swing.JTextField txtSegundos;
    // End of variables declaration//GEN-END:variables
}
